apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname.deployment" . }}
  namespace: {{ .Values.deployment.namespace | default .Values.namespace | default "default" }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  {{- with .Values.deployment.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.deployment.image.registry }}/{{ .Values.deployment.image.repository }}:{{ default "latest" .Values.deployment.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.deployment.image.pullPolicy }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ default 80 .Values.service.port.port }}
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.env }}
          env:
            {{- toYaml .Values.deployment.env | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.secrets.data }}
            - secretRef:
                name: {{ include "mychart.fullname" . }}-secrets
            {{- end }}
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .name }}
      {{- end }}
