{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mychart.fullname.hpa" . }}
  namespace: {{ .Values.autoscaling.namespace | default .Values.namespace | default "default" }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mychart.fullname.deployment" . }}
  minReplicas: {{ default 1 .Values.autoscaling.minReplicas }}
  maxReplicas: {{ default 3 .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 80 .Values.autoscaling.cpu.targetUtilization }}
  {{- end }}
  {{- if .Values.autoscaling.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.memory.targetUtilization }}
  {{- end }}
{{- end }}
