{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ default (include "mychart.fullname" .) .Values.ingressRoute.name }}
  namespace: {{ .Values.ingressRoute.namespace | default .Values.namespace | default "default" }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
  {{- range .Values.ingressRoute.rules }}
    - match: Host(`{{ .host }}`)
      kind: Rule
      services:
        - name: {{ include "mychart.fullname.service" $ }}
          namespace: {{ $.Values.service.namespace | default $.Values.namespace | default "default" }}
          port: {{ $.Values.service.port.port }}
  {{- end }}
{{- end }}
