{{- if .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-secrets
  namespace: {{ .Values.secrets.namespace | default .Values.namespace | default "default" }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
