name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  # In master we want to run for every commit, in other branches — only for the last one
  group: ${{
    ( github.ref == 'refs/heads/master' && format('{0}/{1}/{2}', github.workflow, github.ref, github.sha) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - uses: actions/checkout@v4
      - run: helm lint
      - run: helm template my-release . --debug
